version: '3.8'

services:
  app:
    build: .
    container_name: face_recognition_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root_password
      - MYSQL_DB=face_recognition
    devices:
      - "/dev/video0:/dev/video0"
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: face_recognition
    ports:
      - "3306:3306"
